---
- name: Base setup
  import_playbook: base-setup.yaml

- name: Gitlab MASTER setup
  hosts: gitlab_masters

  vars_files:
    - ../vars/gitlab-secrets.yaml

  tasks:
    - import_tasks: ../tasks/gitlab-docker.yaml
